"""Rename column name to title

Revision ID: bec8bed09d8f
Revises: c184d6724430
Create Date: 2024-01-05 08:34:46.494234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec8bed09d8f'
down_revision: Union[str, None] = 'c184d6724430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('title', sa.String(), nullable=True))
    op.drop_index('ix_products_name', table_name='products')
    op.create_index(op.f('ix_products_title'), 'products', ['title'], unique=False)
    op.drop_column('products', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_products_title'), table_name='products')
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.drop_column('products', 'title')
    # ### end Alembic commands ###
