"""Initial migration

Revision ID: e4452073bb79
Revises: ef2ee0ee1fe5
Create Date: 2024-01-08 16:55:50.837086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4452073bb79'
down_revision: Union[str, None] = 'ef2ee0ee1fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_predict', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_predict')
    # ### end Alembic commands ###
